In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv('data.csv').drop(['Unnamed: 0'], axis=1)
df1 = pd.read_csv('data_nov.csv').drop(['Unnamed: 0'], axis=1)

In [3]:
def f(df):
    for i in range(len(df['цена'])):
        if 'без скидки' in df['цена'][i]:
            df.drop([i], inplace=True)
    return df.reset_index(drop=True)

def price_prepare(prices):
    for i in range(len(prices)):
        price=int(prices[i].replace("₽", "").replace(" ",""))
        prices[i] = price
    return prices

def datasep(df,data,index):
    df['пробег'][index] = int(data[0].replace("км", "").replace(" ", "").strip())
    df['тип двигателя'][index] = data[4].strip()
    df['кузов'][index] = data[2].strip()
    df['привод'][index] = data[3].strip()
    mas = df['описание'][index].strip().split(",")
    w = mas[1].strip().split(' ')
    if len(w) == 4:
        df['объем двигателя'][index] = w[0].strip()
        df['коробка передач'][index] = w[1].strip().lower()
        df['л.с'][index] = w[2].replace("(", "").strip()
    else:
        df.drop([index], inplace=True)
    return df

def specification_prepare(df):
    df['пробег'] = ' '
    df['тип двигателя'] = ' '
    df['объем двигателя'] = ' '
    df['коробка передач'] = ' '
    df['кузов'] = ' '
    df['привод'] = ' '
    df['л.с'] = ' '
    df['состаяние'] = ' '
    for i in range(len(df)):
        arr = df['описание'][i].strip().split(",")
        if len(arr) == 4:
            df = df.drop([i])
        elif len(arr) == 5:
            df['состаяние'][i] = 'не битый'
            datasep(df,arr,i)
        else:
            arr.remove('Битый')
            df['состаяние'][i] = 'битый'
            datasep(df,arr,i)
    df = df.drop(['описание'], axis=1)
    return df.reset_index(drop=True)

def name_prepare(names):
    names['название'] = names['название'].str.lower()
    pattern = re.compile(r'\w+')
    names['год'] = 1
    names['модель'] = ' '
    arr = names['название'].str.lower().str.strip().str.split(",")
    for i, j in enumerate(arr):
        names['год'][i] = j[1]
        word = pattern.findall(j[0])[0]
        model = names['название'][i].replace(word, '').replace(','+j[1], '').strip()
        names['название'][i] = word
        names['модель'][i] = model
    return names

def make_df(df1,df2):
    new_df = pd.concat([df1, df2],ignore_index=True)
    new_df = new_df.loc[new_df['год'] != ' до 1960']
    new_df['год'] = pd.to_numeric(new_df['год'])
    new_df['объем двигателя'] = pd.to_numeric(new_df['объем двигателя'])
    new_df['л.с'] = pd.to_numeric(new_df['л.с'])
    return new_df.reset_index(drop=True)

In [4]:
df1 = f(df1)
df['цена'] = price_prepare(df['цена'])
df = name_prepare(df)
df = specification_prepare(df)
df1['цена'] = price_prepare(df1['цена'])
df1 = name_prepare(df1)
df1 = specification_prepare(df1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [5]:
new_df = make_df(df,df1)

In [6]:
new_df

,название,цена,год,модель,пробег,тип двигателя,объем двигателя,коробка передач,кузов,привод,л.с,состаяние
0,porsche,2950000,2013,cayman,46000,бензин,2.7,amt,купе,задний,275,не битый
1,mitsubishi,470000,2000,eclipse,170000,бензин,3.0,at,купе,передний,208,не битый
2,toyota,850000,2001,land cruiser prado,185200,бензин,3.4,mt,внедорожник,полный,185,не битый
3,kia,659000,2017,rio,18300,бензин,1.4,mt,седан,передний,107,не битый
4,renault,580000,2014,duster,200000,бензин,2.0,at,внедорожник,полный,135,не битый
...,...,...,...,...,...,...,...,...,...,...,...,...
5071,mitsubishi,445000,1993,rvr,300000,бензин,2.0,at,минивэн,полный,160,не битый
5072,daewoo,165000,2012,matiz,99000,бензин,0.8,mt,хетчбэк,передний,52,не битый
5073,bmw,1699000,2013,x6,99500,бензин,3.0,at,внедорожник,полный,306,не битый
5074,bmw,1100000,2013,7 серия,125000,бензин,4.4,at,седан,полный,407,не битый
5075,ваз,40000,1986,2101,38500,бензин,1.2,mt,седан,задний,59,не битый

In [7]:
new_df.to_csv('new_data_frame.csv')